# apache pv
apiVersion: v1
kind: PersistentVolume
metadata:
  name: apache-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/projects" #Dir on minikube VM- run command 'minikube ssh' then create projects in /data dir

#PV claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apache-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
